### ISSUE TITLE
ウィンドウフォーカスについて

### ISSUE THREAD

**Issue by h-shimomichi** [komiyamma/hm_openai_chatgpt35_turbo#1]
いつも有益なソフトウェアありがとうございます。
こんな使い方があるのだといつも参考になります。

ところで、
当該マクロを起動すると、HmChartGPT35Turboのウィンドウが秀丸の前に立上がりますよね。
その後、秀丸以外のウィンドウで操作をして、HmChartGPT35Turboのウィンドウをクリックすると秀丸メールのウィンドウが前にでてきて、HmChartGPT35Turboのウィンドウが秀丸の後に回ってしまいます。
HmChartGPT35Turboのウィンドウをクリックしたら、HmChartGPT35Turboがアクティブになるようにならないものでしょうか？

秀丸側の制限のような気もしますが、、、、

**Comment by komiyamma** [comment]
利用していただいてありがとうございます。

HmChatGPT35Turboのウィンドウのフォーカスについては、「見失いやすい」という問題があることは認識していますので、
1.0.7.1 で改良したものをアップ予定です。
(先ほどreleaseしたばかりですが、秀丸マクロ.net のサイトの方にはまだ記載していません)

多分1,2時間後には、サイトの方の説明文等の記載も終えると思います。

**Comment by komiyamma** [comment]
秀丸マクロ.net の方にもリリースしました。
https://xn--pckzexbx21r8q9b.net/?page=nobu_tool_hm_chatgpt35turbo_update

こちらである程度、フォーカス見失いの問題は解消するかと思います。

**Comment by h-shimomichi** [comment]
おはようございます。
昨晩布団に入ったところでメールが届いているのに気がつきました。
あまりの対応の早さに驚愕です！
1.0.7.1でウィンドウが裏に隠れることが無くなりました。
これ手放せません！ありがとうございました。
