### ISSUE TITLE
トークンを減らすために

### ISSUE THREAD

**Issue by h-shimomichi** [komiyamma/hm_openai_chatgpt35_turbo#2]
おせわになります。

連続するスペースはトークンを消費するので、秀丸のコピーバッファから取込むときにスペースをタブに置換える機能を付けるというのはいかがでしょうか？
たとえばpythonソースを食わせる場合、めちゃくちゃスペースが多いので、かなりトークンを減らせるのではと思います。

ソースあるのだから自分でやれよなのですが(笑)

**Comment by komiyamma** [comment]
@h-shimomichi  さんこんにちわ。

トークンの消費数ですが、細かなOpenAI/ChatGPTのトークン消費アルゴリズムは不明ですが、
概ね

- 「1個のスペース」と「２個のスペース」では「１トークン消費の差」がある。
- しかし、「２個のスペース」と「10個のスペース」ではトークン消費に「差はない」。

よって、「連続したスペース」というトークン消費で済むようになっているのだと思います。

このため、スペースをタブに置き換えることで「異なるものになっている」という副作用と、
トークン消費を抑える効果を天秤にかけると、トークン消費抑制の効果は薄いので、
タブには置き換えないほうが良いと思います。

(副作用：間違った空白関連の文法エラーが正しい文法になってしまうかもしれない、「空白数」自体をChatGPTに問い合わせた時、間違った答えを返してしまう等)

**Comment by h-shimomichi** [comment]
お返事ありがとうございます。

ここで示されているトークン消費量を見ると複数スペースでトークンが上がっていくような気がしたので、先のように思いました。
https://platform.openai.com/tokenizer

おっしゃるように、私もタブとスペース問題で苦労したこともあるので理解しました。

ありがとうございます。
